/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreinscriptionRouteImport } from './routes/preinscription'
import { Route as NotreEcoleRouteImport } from './routes/notre-ecole'
import { Route as FilieresRouteImport } from './routes/filieres'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationsSlugRouteImport } from './routes/formations.$slug'
import { Route as FilieresSlugRouteImport } from './routes/filieres.$slug'

const PreinscriptionRoute = PreinscriptionRouteImport.update({
  id: '/preinscription',
  path: '/preinscription',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreEcoleRoute = NotreEcoleRouteImport.update({
  id: '/notre-ecole',
  path: '/notre-ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const FilieresRoute = FilieresRouteImport.update({
  id: '/filieres',
  path: '/filieres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsSlugRoute = FormationsSlugRouteImport.update({
  id: '/formations/$slug',
  path: '/formations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FilieresSlugRoute = FilieresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FilieresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/filieres': typeof FilieresRouteWithChildren
  '/notre-ecole': typeof NotreEcoleRoute
  '/preinscription': typeof PreinscriptionRoute
  '/filieres/$slug': typeof FilieresSlugRoute
  '/formations/$slug': typeof FormationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/filieres': typeof FilieresRouteWithChildren
  '/notre-ecole': typeof NotreEcoleRoute
  '/preinscription': typeof PreinscriptionRoute
  '/filieres/$slug': typeof FilieresSlugRoute
  '/formations/$slug': typeof FormationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/filieres': typeof FilieresRouteWithChildren
  '/notre-ecole': typeof NotreEcoleRoute
  '/preinscription': typeof PreinscriptionRoute
  '/filieres/$slug': typeof FilieresSlugRoute
  '/formations/$slug': typeof FormationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/contact'
    | '/filieres'
    | '/notre-ecole'
    | '/preinscription'
    | '/filieres/$slug'
    | '/formations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/contact'
    | '/filieres'
    | '/notre-ecole'
    | '/preinscription'
    | '/filieres/$slug'
    | '/formations/$slug'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/contact'
    | '/filieres'
    | '/notre-ecole'
    | '/preinscription'
    | '/filieres/$slug'
    | '/formations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  ContactRoute: typeof ContactRoute
  FilieresRoute: typeof FilieresRouteWithChildren
  NotreEcoleRoute: typeof NotreEcoleRoute
  PreinscriptionRoute: typeof PreinscriptionRoute
  FormationsSlugRoute: typeof FormationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preinscription': {
      id: '/preinscription'
      path: '/preinscription'
      fullPath: '/preinscription'
      preLoaderRoute: typeof PreinscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-ecole': {
      id: '/notre-ecole'
      path: '/notre-ecole'
      fullPath: '/notre-ecole'
      preLoaderRoute: typeof NotreEcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filieres': {
      id: '/filieres'
      path: '/filieres'
      fullPath: '/filieres'
      preLoaderRoute: typeof FilieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/$slug': {
      id: '/formations/$slug'
      path: '/formations/$slug'
      fullPath: '/formations/$slug'
      preLoaderRoute: typeof FormationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filieres/$slug': {
      id: '/filieres/$slug'
      path: '/$slug'
      fullPath: '/filieres/$slug'
      preLoaderRoute: typeof FilieresSlugRouteImport
      parentRoute: typeof FilieresRoute
    }
  }
}

interface FilieresRouteChildren {
  FilieresSlugRoute: typeof FilieresSlugRoute
}

const FilieresRouteChildren: FilieresRouteChildren = {
  FilieresSlugRoute: FilieresSlugRoute,
}

const FilieresRouteWithChildren = FilieresRoute._addFileChildren(
  FilieresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  ContactRoute: ContactRoute,
  FilieresRoute: FilieresRouteWithChildren,
  NotreEcoleRoute: NotreEcoleRoute,
  PreinscriptionRoute: PreinscriptionRoute,
  FormationsSlugRoute: FormationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
